import React from 'react';
import { ArrowUpRight, Building2, CarFront, Compass, Leaf } from 'lucide-react';
import SafeImage from '../components/ui/SafeImage';
import { IMG } from '../data/site';
import { contactConfig } from '../config/contact';

export default function About(){return <main className="page-shell">
<section className="relative min-h-[68vh] overflow-hidden bg-[#102A20] text-white"><SafeImage src={IMG.forest} alt="Corbett forest" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0B2119] via-[#0B2119]/55 to-[#0B2119]/15"/><div className="container-wide relative z-10 flex min-h-[68vh] items-end pb-16 pt-32"><div><p className="eyebrow text-[#D8C49A]">ABOUT JIM CORBETT ADVENTURES</p><h1 className="display mt-4 max-w-5xl text-6xl md:text-8xl">A local connection<br/>to the wild.</h1></div></div></section>
<section className="container-wide py-16 md:py-24"><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="eyebrow">OUR STORY</p><h2 className="display mt-3 text-4xl md:text-6xl">Rooted in<br/>the forest.</h2></div><div className="space-y-5 body-copy text-lg"><p>Jim Corbett Adventures is presented on the client site as the official direct booking portal of Bigcat Corbett, a Destination Management Company and direct ground handler based in Ramnagar.</p><p>The client’s About page describes a family legacy in wildlife tourism, built around the late Chandra Shekhar Khulbe, a naturalist whose tracking instincts, forest knowledge and conservation-minded approach shaped the team.</p><p>The operating model connects safari planning, local transfers, accommodation, dining, naturalist-led experiences, corporate retreats and customised itineraries through one local ecosystem.</p></div></div></section>
<section className="bg-[#102A20] py-16 text-white md:py-20"><div className="container-wide grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Feature icon={Compass} title="Local expertise" text="Ramnagar-based coordination close to the destination."/><Feature icon={CarFront} title="Ground handling" text="Transfers, safari planning and local logistics."/><Feature icon={Building2} title="Hospitality" text="Stay, dining and safari coordination through a connected network."/><Feature icon={Leaf} title="Wildlife focus" text="Experiences shaped around the forest and responsible tourism."/></div></section>
<section className="container-wide py-16 md:py-24"><div className="grid items-center gap-10 lg:grid-cols-2"><div className="overflow-hidden rounded-[24px]"><SafeImage src={IMG.jeep} alt="Jeep safari" className="h-[420px] w-full object-cover"/></div><div><p className="eyebrow">WHO WE SERVE</p><h2 className="display mt-3 text-4xl md:text-5xl">Travellers, groups<br/>and travel partners.</h2><div className="mt-6 space-y-4 text-sm leading-7 text-[#102A20]/65"><p>Families and couples can plan stays, safaris and activities around their dates.</p><p>Travel agents can request B2B net rates and ground-handling support.</p><p>Corporate groups can build customised retreats with transport, accommodation, dining and activities.</p></div><a href={contactConfig.whatsappUrl} className="btn-dark mt-7">Talk to the local team <ArrowUpRight size={15}/></a></div></div></section>
</main>}
const Feature=({icon:Icon,title,text})=><div className="rounded-[20px] border border-white/10 bg-white/5 p-6"><Icon className="text-[#D8C49A]" size={20}/><h3 className="mt-6 font-serif text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></div>;
