import React from 'react';
import { useParams, Link } from 'react-router-dom';
import SafeImage from '../components/ui/SafeImage';
import { IMG } from '../data/site';
import { posts } from './Blog';

const body={
 'dhikala-vs-bijrani':[['The short answer','Dhikala and Bijrani are both important Corbett landscapes, but they are not interchangeable. Dhikala is known for broad grasslands, the Ramganga landscape and a deeper wilderness feel. Day visitors experience the zone through the Canter format, while overnight forest-stay arrangements can open different possibilities. Bijrani is closer to Ramnagar and combines Sal forest with open areas, making it a strong day-safari option.'],['Choose by experience','If you want the iconic, expansive Corbett landscape and are interested in an overnight wilderness stay, ask about Dhikala. If you want a day-focused jeep safari with a classic Sal-forest setting, ask about Bijrani. Availability and official access should always decide the final choice.'],['A practical rule','Do not choose a zone only because someone promises tiger sightings. Wildlife is unpredictable. Choose a landscape you will enjoy spending several hours observing.']],
 'full-day-corbett-rafting':[['The journey','The client site describes a full-day route from Kumeriya to Dhikuli, with a safety briefing at Kumeriya and a stop around Mohaan for refreshments. The landscape shifts from active river sections to quieter forest views.'],['Why monsoon changes the experience','During the rainy season the river becomes livelier and the forest turns intensely green. The activity remains dependent on real-time water conditions and local safety clearances.'],['Plan it with a safari','Rafting can be paired with a jungle safari for travellers who want both water and wildlife in one Corbett trip.']],
 'best-time-to-visit-corbett':[['Summer','March to June is often associated with warmer conditions and wildlife activity around water sources. The client site also describes summer as a strong period for tiger-focused safari experiences.'],['Monsoon','July to September can transform the landscape into a vivid green world, but river activities and safari access become highly weather-dependent.'],['Winter','October to February brings cooler weather and is a popular safari period. Early mornings can be cold, so layers are useful.']],
 'adventure-in-corbett':[['Beyond safari','The client site lists rafting, rope courses, hot air balloon rides, paramotor experiences, ATV rides and bungee jumping alongside the classic safari formats.'],['Build a balanced day','Pair a high-energy activity with a slower forest experience. A morning adventure can be followed by a relaxed resort lunch, sunset experience or evening planning session.']],
 'best-jeep-safari-zone':[['There is no single best zone','The client site highlights Bijrani, Jhirna, Dhela, Garjiya and Durga Devi as key jeep-safari landscapes, with Phato, Sitabani and other buffer areas also appearing in its wider zone information.'],['Match zone to landscape','Choose based on your interests: grasslands, Sal forest, riverine scenery, birding, quieter routes or a specific stay plan. Permit and seasonal availability should be checked before confirmation.']],
 'kosi-river-rafting':[['The Kosi experience','Rafting changes the pace of a Corbett trip. Instead of looking for movement in the forest, you read the river, rapids, banks and changing light.'],['Routes and conditions','The client site lists short and longer rafting options, including a 4.5 km beginner-friendly run and a 13 km extreme route. Water conditions, weather and safety clearance can affect operations.']]
};
export default function BlogPost(){const {slug}=useParams();const p=posts.find(x=>x.slug===slug)||posts[0];const sections=body[slug]||body['dhikala-vs-bijrani'];return <main className="page-shell"><section className="container-wide pt-32 pb-10 md:pt-40"><Link to="/blog" className="eyebrow">← ALL STORIES</Link><h1 className="display mt-5 max-w-5xl text-5xl md:text-7xl">{p.title}</h1><p className="mt-5 text-xs uppercase tracking-[0.18em] text-[#102A20]/45">{p.date} · Jim Corbett Adventures</p><div className="mt-10 h-[360px] overflow-hidden rounded-[24px] md:h-[560px]"><SafeImage src={p.image} alt={p.title} className="h-full w-full object-cover"/></div></section><article className="container-wide pb-20"><div className="mx-auto max-w-3xl space-y-12">{sections.map(([h,t])=><section key={h}><h2 className="font-serif text-3xl md:text-4xl">{h}</h2><p className="mt-4 text-base leading-8 text-[#102A20]/70">{t}</p></section>)}</div></article></main>}
